"""Add address field to SafeZone model

Revision ID: 8a9499212c90
Revises: 
Create Date: 2024-12-30 20:09:11.246577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9499212c90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safe_zone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safe_zone', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
