"""Update Notification model with safe zone tracking

Revision ID: d73c5fd75531
Revises: 61fd42456d76
Create Date: 2024-12-30 20:55:58.158361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73c5fd75531'
down_revision = '61fd42456d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safe_zone_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_inside', sa.Boolean(), nullable=False))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'safe_zone', ['safe_zone_id'], ['id'])
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['parent_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('is_inside')
        batch_op.drop_column('safe_zone_id')

    # ### end Alembic commands ###
